[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/vault"
  branch = "master"

[[constraint]]
  name = "github.com/mgutz/logxi"
  version = "1.0.0"

[[constraint]]
  name = "github.com/nlopes/slack"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
